# Generated by Django 5.1.4 on 2024-12-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='city',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='message',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='email_id',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
