# Generated by Django 5.1.4 on 2024-12-18 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_city_paymenttransaction_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='email_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
